apiVersion: v1
kind: Service
metadata:
  name: campuscare-backend-service
  namespace: {{ .Values.namespace | default "campuscare" }}
  labels:
    app.kubernetes.io/name: campuscare
    app.kubernetes.io/component: backend-service
    app.kubernetes.io/part-of: campuscare
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port | default 5000 }}
      targetPort: {{ .Values.backend.service.port | default 5000 }}
      protocol: TCP
      name: http-api
  selector:
    app: campuscare-backend
