apiVersion: v1
kind: Secret
metadata:
  name: campuscare-secret
  namespace: {{ .Values.namespace | default "campuscare" }}
  labels:
    app.kubernetes.io/name: campuscare
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: campuscare
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
