apiVersion: v1
kind: ConfigMap
metadata:
  name: campuscare-config
  namespace: campuscare
  labels:
    app.kubernetes.io/name: campuscare
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: campuscare
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGO_HOST: "campuscare-mongodb-service"
