apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: campuscare-uploads-pvc
  namespace: campuscare
  labels:
    app.kubernetes.io/name: campuscare
    app.kubernetes.io/component: uploads-storage
    app.kubernetes.io/part-of: campuscare
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
